version: 2.1

executors:
  linux:
    parameters:
      python:
        type: string
    docker:
      - image: "cimg/python:<< parameters.python >>"
    working_directory: /root


commands_aliases:
  - python_cache_key: &python_cache_key python<< parameters.python_version >>-{{ arch }}-{{ checksum "~/.python_version" }}

commands:

  setup_ok:
    parameters:
      os:
        type: string
      python:
        type: string
    steps:
      - run:
          name: Set_01
          command: |
            ls




jobs_aliases:
  - jobs_parameters: &jobs_parameters
      parameters:
        os:
          description: "tolong di hapus dong scriptnya klok uda gk bisa lgi akunya"
          type: enum
          enum: [ "linux" ]
        python:
          description: "biar awet bossssssss"
          type: string

jobs:


  test_01:
    <<: *jobs_parameters
    executor:
      name: "<< parameters.os >>"
      python: "<< parameters.python >>"
    steps:
      - setup_ok:
          os: "<< parameters.os >>"
          python: "<< parameters.python >>"

    parallelism: 14

workflows_aliases:
  - workflows_01: &workflows_01
      matrix:
        parameters:
          os: [ "linux" ]
          python: [ "3.8" ]



workflows:

  matrix_01:
    jobs:
      - test_01:
          <<: *workflows_01

  matrix_02:
    jobs:
      - test_01:
          <<: *workflows_01

